<a href="https://colab.research.google.com/github/tejaspradhan/Graph-Neural-Networks/blob/main/code/GNN_Spektral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installing Spektral

In [1]:
!pip install spektral

     |████████████████████████████████| 123 kB 7.3 MB/s 


## Importing Libraries

In [2]:
import numpy as np
from spektral.datasets import TUDataset
from spektral.transforms import Degree, GCNFilter
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout
from spektral.layers import GCNConv, GlobalSumPool
from spektral.data import BatchLoader

## Exploring the Dataset

In [3]:
dataset = TUDataset("PROTEINS")

100%|█████████████████████████████████████████| 447k/447k [00:00<00:00, 897kB/s]


Successfully loaded PROTEINS.


In [4]:
dataset
# this dataset has 1113 distinct graphs

TUDataset(n_graphs=1113)

In [5]:
dataset.n_labels

2

Exploring 1 graph

In [6]:
graph = dataset[0]
graph

Graph(n_nodes=42, n_node_features=4, n_edge_features=None, n_labels=2)

In [7]:
# Adjacency Matrix
graph.a

<42x42 sparse matrix of type '<class 'numpy.float64'>'
	with 162 stored elements in Compressed Sparse Row format>

In [8]:
# Node Feature Matrix
graph.x

array([[23.,  1.,  0.,  0.],
       [10.,  1.,  0.,  0.],
       [25.,  1.,  0.,  0.],
       [ 7.,  1.,  0.,  0.],
       [12.,  1.,  0.,  0.],
       [11.,  1.,  0.,  0.],
       [ 5.,  1.,  0.,  0.],
       [ 7.,  1.,  0.,  0.],
       [ 9.,  1.,  0.,  0.],
       [ 3.,  1.,  0.,  0.],
       [ 6.,  1.,  0.,  0.],
       [22.,  1.,  0.,  0.],
       [ 8.,  1.,  0.,  0.],
       [26.,  1.,  0.,  0.],
       [ 7.,  1.,  0.,  0.],
       [12.,  1.,  0.,  0.],
       [11.,  1.,  0.,  0.],
       [ 5.,  1.,  0.,  0.],
       [ 7.,  1.,  0.,  0.],
       [ 8.,  1.,  0.,  0.],
       [ 3.,  1.,  0.,  0.],
       [ 6.,  1.,  0.,  0.],
       [ 3.,  0.,  1.,  0.],
       [ 9.,  0.,  1.,  0.],
       [10.,  0.,  1.,  0.],
       [ 7.,  0.,  1.,  0.],
       [10.,  0.,  1.,  0.],
       [ 8.,  0.,  1.,  0.],
       [ 5.,  0.,  1.,  0.],
       [ 4.,  0.,  1.,  0.],
       [ 3.,  0.,  1.,  0.],
       [ 3.,  0.,  1.,  0.],
       [ 3.,  0.,  1.,  0.],
       [ 9.,  0.,  1.,  0.],
       [10.,  

In [9]:
# Edge Feature Matrix. No Edge Features for this graph
graph.e

In [10]:
# Label Matrix
graph.y

array([1., 0.])

Datasets also provide methods for applying transforms to each datum:

`apply(transform)` - modifies the dataset in-place, by applying the transform to each graph

`map(transform)` - returns a list obtained by applying the transform to each graph

`filter(function)` - removes from the dataset any graph for which function(graph) is False. This is also an in-place operation.

In [11]:
dataset.filter(lambda g: g.n_nodes < 500) # removing those graphs from the dataset which have >= 500 nodes
dataset 

TUDataset(n_graphs=1111)

## Preprocessing the Dataset for the GNN 

In [12]:
# Finding the maximum degree of the data
max_degree = int(dataset.map(lambda g: g.a.sum(-1).max(), reduce=max))

In [13]:
max_degree 

12

Augmenting the Dataset's Node Features with the Maximum Degree of any Graph 

In [14]:
dataset.apply(Degree(max_degree))

In [15]:
dataset[0].x

array([[23.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [10.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [25.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 7.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [12.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [11.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 5.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 7.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 9.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 3.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         

Doing Feature preprocessing for Graph Convolutional Layer

In [16]:
dataset.apply(GCNFilter())

## Creating the GNN

In [38]:
class GNN(Model):
  def __init__(self, n_hidden, n_labels):
    super().__init__()
    self.graph_conv = GCNConv(n_hidden)
    self.pool = GlobalSumPool()
    self.dropout = Dropout(0.5)
    self.dense1 = Dense(100,activation='relu')
    self.dense2 = Dense(n_labels, 'softmax')
  
  def call(self, inputs):
    model = self.graph_conv(inputs)
    #model = self.dropout(model)
    model = self.pool(model)
    model = self.dense1(model)
    model= self.dense2(model)
    ### GCN --> Dropout--> Global Sum Pool --> Dense
    return model

In [39]:
model = GNN(64,dataset.n_labels) # Instantiating the Model

In [40]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

## Training the GNN 

In [41]:
loader = BatchLoader(dataset, batch_size=32)

In [42]:
model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=10)

Epoch 1/10
35/35 [==============================] - 1s 24ms/step - loss: 4.9128 - accuracy: 0.5923
Epoch 2/10
35/35 [==============================] - 1s 23ms/step - loss: 1.1981 - accuracy: 0.6184
Epoch 3/10
35/35 [==============================] - 1s 23ms/step - loss: 1.4708 - accuracy: 0.6058
Epoch 4/10
35/35 [==============================] - 1s 24ms/step - loss: 2.1087 - accuracy: 0.6544
Epoch 5/10
35/35 [==============================] - 1s 24ms/step - loss: 1.4967 - accuracy: 0.6193
Epoch 6/10
35/35 [==============================] - 1s 25ms/step - loss: 1.3296 - accuracy: 0.6409
Epoch 7/10
35/35 [==============================] - 1s 24ms/step - loss: 1.4893 - accuracy: 0.6292
Epoch 8/10
35/35 [==============================] - 1s 22ms/step - loss: 1.2094 - accuracy: 0.6580
Epoch 9/10
35/35 [==============================] - 1s 23ms/step - loss: 1.1800 - accuracy: 0.6724
Epoch 10/10
35/35 [==============================] - 1s 22ms/step - loss: 0.8644 - accuracy: 0.6868


Model: "gnn"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gcn_conv (GCNConv)          multiple                  576       
                                                                 
 global_sum_pool (GlobalSumP  multiple                 0         
 ool)                                                            
                                                                 
 dropout (Dropout)           multiple                  0         
                                                                 
 dense (Dense)               multiple                  66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________
